version: '3.5'

services:
  app:
    build: .
    image: mqttocampus
    # container-name implies only one instance
    container_name: mqttocampus
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- .:/opt/app
    network_mode: bridge
    ports:
      - "10483:1883"    # MQTT TCP
      #- "10488:8883"    # MQTTS TCP
      - "10491:9001"    # MQTT WS
      #- "10498:9883"    # MQTT WSS
      - "2220:22"       # SSH
    environment:
      # DON'T USE localhost to communicate with others services in 'bridge' mode
      # ... instead set 172.17.0.1 which is the docker gateway
      # DEBUG is the app. debugging feature
      # FLASK_ENV=development activate ALL flask debug features
      # FLASK_DEBUG as you guessed ;)
      - PYTHONUNBUFFERED=1
      # MQTT default configuration file
      - MQTT_CONFIG_FILE="neocampus.conf"
      # FLASK
      - FLASK_DEBUG
      - FLASK_ENV
      - DEBUG

